- type: entity
  id: ShredderMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: shredder machine board
  description: A machine printed circuit board for a shredder.
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: Shredder

- type: entity
  id: SalvageTechFabCircuitboardNF
  parent: BaseMachineCircuitboard
  name: salvage techfab machine board
  description: A machine printed circuit board for a salvage techfab
  components:
    - type: Sprite
      state: supply
    - type: MachineBoard
      prototype: SalvageTechfabNF

# TechFab
- type: entity
  id: NfsdTechFabCircuitboard
  parent: SecurityTechFabCircuitboard
  name: nfsd techfab machine board
  description: A machine printed circuit board for an nfsd techfab.
  components:
    - type: Sprite
      state: supply
    - type: MachineBoard
      prototype: NfsdTechFab

# Thrusters
- type: entity
  id: ThrusterSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: security thruster machine board
  components:
  - type: MachineBoard
    prototype: ThrusterSecurity

- type: entity
  id: ThrusterNfsdMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: nfsd thruster machine board
  components:
  - type: MachineBoard
    prototype: ThrusterNfsd

- type: entity
  id: SmallThrusterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: small thruster machine board
  components:
  - type: MachineBoard
    prototype: SmallThruster
  - type: StaticPrice
    price: 12.5

# Gyroscope
- type: entity
  id: GyroscopeSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: security gyroscope machine board
  components:
  - type: MachineBoard
    prototype: GyroscopeSecurity

- type: entity
  id: SmallGyroscopeSecurityMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: small security gyroscope machine board
  components:
  - type: MachineBoard
    prototype: SmallGyroscopeSecurity
  - type: StaticPrice
    price: 12.5

- type: entity
  id: GyroscopeNfsdMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: nfsd gyroscope machine board
  components:
  - type: MachineBoard
    prototype: GyroscopeNfsd

- type: entity
  id: SmallGyroscopeNfsdMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: small nfsd gyroscope machine board
  components:
  - type: MachineBoard
    prototype: SmallGyroscopeNfsd
  - type: StaticPrice
    price: 12.5

- type: entity
  id: SmallGyroscopeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: small gyroscope machine board
  components:
  - type: MachineBoard
    prototype: SmallGyroscope
  - type: StaticPrice
    price: 12.5
